pycurl/pycurl

- examples/basicfirst.py
- examples/retriever.py
- examples/smtp.py
- examples/xmlrpc_curl.py
Hello,
I've fixed some python3 issues in example scripts.
> Fix python3 compatibility issues in examples

- INSTALL.rst
> pip recompilation instructions

- src/easy.c
Fix a memory leak in Python 2 when passing a unicode object
to a curl object's POSTFIELDS setopt where the str object
created from the passed in unicode object would be leaked on
the successful path.
Fix memory leak in the curl object's POSTFIELDS setopt where
if the curl_easy_setopt CURLOPT_POSTFIELDSIZE or
CURLOPT_POSTFIELDSIZE_LARGE failed the str object created
from the passed in unicode object would be leaked.
-------------------------------------------------------------------------------------------------------------------------
Two sections below show before and after the patch:
1. Create initial state pycurl curl object, str and unicode object of 1000 characters
2. View initial memory
3. Call setopt POSTFIELDS on the curl object with the str 400000 times.
4. View memory.
5. Call …
> Fix memory leaks in curl's POSTFIELDS setopt for unicode objects.

- ChangeLog
- tests/memory_mgmt_test.py
> Changelog entry and test for #262

- ChangeLog
- src/easy.c
- tests/memory_mgmt_test.py
> Setopt httppost memleak

- ChangeLog
- setup.py
- tests/setup_test.py
- tests/travis/run.sh
Extracted from #212 to figure out why the tests fail for libressl in #212.
> Ssl setup refactoring

- .gitignore
- ChangeLog
- INSTALL.rst
- Makefile
- setup.py
- src/module.c
- tests/fake-curl/libcurl/Makefile
- tests/fake-curl/libcurl/with_gnutls.c
- tests/fake-curl/libcurl/with_nss.c
- tests/fake-curl/libcurl/with_openssl.c
- tests/fake-curl/libcurl/with_unknown_ssl.c
- tests/fake-curl/libcurl/without_ssl.c
- tests/setup_test.py
- tests/travis/run.sh
> SSL detection via ctypes

- ChangeLog
- setup.py
- tests/bin/realpath
- tests/ext/test-suite.sh
- tests/getinfo_test.py
- tests/travis/setup.sh
> Autodetect ssl on centos6

- .travis.yml
- Makefile
- tests/run-quickstart.sh
- tests/travis/run.sh
> Run quickstart examples in CI

- ChangeLog
- src/pycurl.h
> Win81 build fix

- doc/callbacks.rst
- tests/close_socket_cb_test.py
- tests/default_write_cb_test.py
- tests/header_cb_test.py
- tests/read_cb_test.py
- tests/seek_cb_constants_test.py
- tests/seek_cb_test.py
- tests/sockopt_cb_test.py
- tests/ssh_key_cb_test.py
> Rename callback tests

- ChangeLog
- src/module.c
- tests/version_constants_test.py
There is one constants that only exists in libcurl 7.47.0 which is not released yet :)
> Add VERSION_* constants

- src/easy.c
- src/pycurl.h
- tests/open_socket_cb_test.py
- tests/util.py
> Add Unix socket support to opensocket callback

- src/easy.c
These fields are longs, not shorts.
> Flowinfo scope fix

- ChangeLog
- python/curl/__init__.py
> Windows signal fix for curl module

- .travis.yml
- tests/util.py
> Test against development versions of libcurl

- src/easy.c
- tests/setopt_test.py
This allows to unset the Accent-Encoding header.
> Allow to unset ENCODING

- src/easy.c
- tests/multi_socket_select_test.py
- tests/setopt_test.py
> Fix for resume from values > 2 gb

- doc/quickstart.rst
Alternate solution to #416, fixes #415.
Original patch by Rodrigo Zanatta Silva.
> Multi-value header fix

- doc/index.rst
- doc/thread-safety.rst
> Document thread safety

- doc/docstrings/curl_getinfo.rst
- doc/quickstart.rst
- examples/quickstart/file_upload_buffer.py
- examples/quickstart/file_upload_real.py
- examples/quickstart/file_upload_real_fancy.py
- examples/quickstart/form_post.py
- examples/quickstart/write_file.py
> Use httpbin over sourceforge, closes #363

- src/easy.c
- src/module.c
- src/pycurl.h
> Adds support for CURLINFO_HTTP_VERSION

- ChangeLog
- requirements-dev.txt
- src/easy.c
- tests/error_test.py
- tests/readdata_test.py
- tests/util.py
- tests/write_test.py
> Bugfix writedata

- doc/index.rst
- doc/troubleshooting.rst
- requirements-dev.txt
> Troubleshooting documentation

- doc/troubleshooting.rst
> Troubleshooting documentation improvements

- src/module.c
>  BoringSSL support without test coverage

- .travis.yml
- tests/option_constants_test.py
- tests/travis/run.sh
- tests/travis/setup.sh
> Test openssl 1.0 and 1.1 on travis

- tests/memory_mgmt_test.py
- tests/util.py
> Check refcount management for readdata etc.

- ChangeLog
- doc/docstrings/multi_add_handle.rst
- src/easy.c
- src/module.c
- src/multi.c
- src/pycurl.h
- src/share.c
- tests/multi_memory_mgmt_test.py
- tests/weakref_test.py
>  Keep Curl objects alive when they are being used by CurlMulti objects 

- ChangeLog
- Makefile
- doc/curlobject.rst
- doc/docstrings/curl_getinfo.rst
- doc/docstrings/curl_getinfo_raw.rst
- src/easy.c
- src/pycurl.h
- tests/app.py
- tests/certinfo_test.py
- tests/getinfo_test.py
- tests/util.py
> Add getinfo_raw

- ChangeLog
- MANIFEST.in
- Makefile
- doc/curlobject.rst
- doc/docstrings/curl_errstr.rst
- doc/docstrings/curl_errstr_raw.rst
- setup.py
- src/easy.c
- src/pycurl.h
- src/stringcompat.c
- src/util.c
- tests/app.py
- tests/failonerror_test.py
> Improve resiliency of FAILONERROR and errstr in face of undecodable data

- ChangeLog
- doc/curlobject.rst
- doc/docstrings/curl_perform_rb.rst
- doc/docstrings/curl_perform_rs.rst
- src/easy.c
- src/easyopt.c
- src/easyperform.c
- src/module.c
- src/pycurl.h
- tests/app.py
- tests/perform_test.py
> Add perform_rb and perform_rs methods to return body from perform.

- winbuild.py
> Depend on nghttp2 in windows

- .github/ISSUE_TEMPLATE.md
- ChangeLog
- setup.py
- tests/setup_test.py
> Setup ssl library diagnostics & fix for non-recognized SSL backends

- appveyor.yml
- winbuild.py
I don't think this will be merged, but I'm just making this draft to experiment with Python 3.7 support on Windows at least.
> Python 37 appveyor experimental

- setup.py
> Fix author email for pypi wheel uploads

- README.rst
> Add appveyor badge

- requirements-dev.txt
> Restrict bottle version to obtain the old behavior

- INSTALL.rst
- doc/thread-safety.rst
- setup.py
> Explcitly mention LibreSSL and BoringSSL in documentation

- src/pythoncompat.c
- tests/curl_object_test.py
> Improve error message when accessing/deleting nonexistent attributes.

- tests/info_test.py
> Test SSL_ENGINES option.

- setup.py
> Fix darwin check.

- winbuild.py
Update c-ares to most recent version.
Related: https://github.com/pycurl/pycurl/issues/585
> update cares_version 1.15.0 in winbuild

- src/multi.c
> Allow threads where callbacks can be invoked

- .travis.yml
> Test python 3.7 in travis

- setup.py
Fix to install on CentOS (tested with CentOS 7.7)
> Fix for #601

- README.kr.rst
Hi:) Do you remember that I wanted to contribute README translation? Finally I am done with it. And you wanted to translate the first half. So we translated to the SUPPORT section. Our team member eourm20 uploaded it. We want you to check the README.kr.rst file. Let me know if there's anything wrong. And we hope you can commit this contribution. Thank you:)
> README KOREAN

- src/easyinfo.c
Requested in https://curl.se/mail/curlpython-2021-05/0000.html
> Allow to get CURLINFO_CONDITION_UNMET

- doc/docstrings/multi_select.rst
> multi_select docs: fix return value on timeout

- tests/multi_callback_test.py
Related to #729.
The easy.pause() test now requests `/long_pause` from the test server and pauses the transfer only after the first part of the body has been received. Hopefully this ensures the correct transfer state for testing easy.pause() callbacks. The mock event loop and socket bookkeeping has been improved as well.
The mock event loop in the other tests has been replaced by just a kick-start since these tests don't depend on the socket state.
@swt2c
Does this pass on your end?
> [WIP] Improve multi_callback_test

- .github/workflows/cibuildwheel.yml
This PR builds Linux wheels for Python 3.7-3.10
> Let CI build 3.7-3.10

- src/module.c
- tests/option_constants_test.py
Added missing CURL_HTTP_VERSION_3ONLY constant.
> Added constant for CURL_HTTP_VERSION_3ONLY

- src/easyinfo.c
- src/module.c
- tests/getinfo_test.py
Added [EFFECTIVE_METHOD](https://curl.se/libcurl/c/CURLINFO_EFFECTIVE_METHOD.html) option for `getinfo()` and `getinfo_raw()`.
> Added EFFECTIVE_METHOD info option

- examples/multi-socket_action-select.py
> Fix minor bug in examples/multi-socket_action-select.py

- .github/workflows/ci-macos.yml
- .github/workflows/ci-windows.yml
- .github/workflows/ci.yml
- .github/workflows/cibuildwheel.yml
- pyproject.toml
- tests/option_constants_test.py
> Build wheels with brotli support

- src/easyopt.c
- src/module.c
- tests/option_constants_test.py
- tests/run.sh
- tests/util.py
https://curl.se/libcurl/c/CURLOPT_ECH.html
> Support setting CURLOPT_ECH
