pycurl/pycurl

ChangeLog, doc/callbacks.rst, src/easy.c, tests/app.py, tests/debug_test.py
=> Debugfunction now is passed a bytestring in second argument

ChangeLog, src/easy.c, tests/open_socket_cb_test.py
=> Use bytes for OPENSOCKETFUNCTION address with AF_UNIX, as documented

src/easy.c
this fixes easy.c wouldn't compile on Solaris #399
=> easy.c wouldn't compile on Solaris

Makefile
We need to be able to build with pyflakes-3.X.
=> Allow overriding of pyflakes executable

src/easy.c, src/multi.c, src/share.c
The Py_TRASHCAN_SAFE_* macros create a lexical block that may or may
not be executed depending on the stack depth. If it's not executed,
the deallocator is called again when the stack is not so deeply
nested. The current curl deallocators have the problem that if the
block is not executed, the object is still freed because
Py_TYPE(self)->tp_free is called outside of the trashcan block. This
can lead to double-freeing.
=> end trashcan sections after calling free

winbuild.py
The bug in #433 is fixed in c-ares 1.11.0. This updates c-ares to the latest version 1.12.0.
=> Update to c-ares 1.12.0 in Windows builds, fixing #433

src/module.c
Does it need to decrement reference count if v if insobj2() failed?
=> Decrement reference count if insobj2() failed.

examples/retriever-multi.py, examples/retriever.py, examples/tests/test_gtk.py, examples/xmlrpc_curl.py, python/curl/__init__.py
The current code in some examples would crash on systems without `SIGPIPE`, since it would raise an AttributeError instead of ImportError, which was not being caught in the `except` statement.
I also moved the `signal.signal()` call to an `else:` clause, to make the exception handling more specific.
Finally I made the code and comments identical in all examples, for consistency.
=> fix and standardize ignoring of SIGPIPE in examples

src/module.c
Make the build reproducible:
* Removed compile date-timestamp 
Based on the reproducible-builds effort https://reproducible-builds.org/docs/timestamps/
=> reproducible builds fix - remove compile timestamp

winbuild.py
`NotImplemented` is a sentinel object, not an exception type.
It was mistakenly used instead of `NotImplementedError`.
=> Fix raising NotImplementedError

tests/ssh_key_cb_test.py
Since version 7.58.0, curl may be compiled with libssh
instead of libssh2 which differs in the supported functionality.
For example CURLOPT_SSH_KNOWNHOSTS and CURLOPT_SSH_KEYFUNCTION
are unknown options to curl in such setup.
=> Update tests to work with curl compiled with libssh

ChangeLog, src/threadsupport.c
=> use up-to-date OpenSSL API to control thread locks

ChangeLog, setup.py, tests/fake-curl/curl-config-ssl-in-libs, tests/fake-curl/curl-config-ssl-in-static-libs, tests/setup_test.py
- Do not attempt to automatically detect SSL backend if curl is not
compiled with SSL support.
- Warn if curl is compiled without SSL support and SSL backend is
manually specified in setup.py.
- If curl is compiled with SSL support, require setup.py to know what
SSL backend is being used rather than failing later at extension
compilation.
Fixes #290
=> SSL backend detection logic refactoring.

winbuild.py, winbuild/libcurl-fix-zlib-references.patch
This is intended to support adding nghttp2 later, as well as fixes to build against current dependencies (c-ares 1.14.0 and libcurl 7.60.0 in particular break current winbuild).
7.60.0 breakage: https://github.com/curl/curl/pull/2474
=> Winbuild refactoring

python/curl/__init__.py
In the `__init__` function `self.hdr` is mistyped as `self.hrd` and a mutable object (`[]`) is used in the function definition.
=> Fix two small bugs in python/curl/__init__.py

appveyor.yml
This removes the stderr message that causes Appveyor to fail pip callin'
commands.
=> Disable pip version check by environment variable on appveyor

src/easyopt.c, src/multi.c
```
Error: UNREACHABLE (CWE-561):
pycurl-7.43.0.2/src/multi.c:631: unreachable: This code cannot be reached: "PyDict_DelItem(self->easy_o...".
629|       if (res != CURLM_OK) {
630|           CURLERROR_MSG("curl_multi_add_handle() failed due to internal errors");
631|->         PyDict_DelItem(self->easy_object_dict, (PyObject *) obj);
632|       }   
633|       obj->multi_stack = self;
Error: UNINIT (CWE-457):
pycurl-7.43.0.2/src/easyopt.c:493: var_decl: Declaring variable "res" without initializer.
pycurl-7.43.0.2/src/easyopt.c:524: uninit_use_in_call: Using uninitialized value "(int)res" when calling "create_and_set_error_object".
522|               if (PyText_AsStringAndSize(httppost_option, &cstr, &clen, &cencoded_obj)) {
523|                   PyText_EncodedDecref(nencoded_obj); …
```
=> fix programming mistakes detected by static analyzers

src/easyinfo.c
Under Python3 the call curl.getinfo(pycurl.INFO_COOKIELIST) returns
invalid list (for example `[<NULL>]`), which cases segmentation fault.
The cause is in function decode_string_list() (Python3 only) which
creates new list without populating it with elements. This commit
adds the setting of elements fixing the behaviour.
=> decode_string_list: fix populating list of decoded strings

ChangeLog, INSTALL.rst, doc/thread-safety.rst, setup.py, src/module.c, src/pycurl.h, src/threadsupport.c
This pull request adds [mbedTLS](https://tls.mbed.org/) support for pycurl. mbedTLS is by default used in OpenWrt routers and without it, I can use OpenSSL or other SSL libraries, which are in OpenWrt, but I will need to compile libcurl with OpenSSL by myself, which is not so hard for me, but I can imagine for other users that it will be a little hard.
What I'm not sure is about file threadsupport.c in folder src.
I have been able to test it with mbedTLS version 2.16.0 and run the following tests, which are documented on [your website](http://pycurl.io/docs/latest/quickstart.html). 
- Following Redirects
- Working With HTTPS
Any feedback regarding it, will be **highly** appreciated as it will help me in for https://github.com/openwrt/packages/pull/8325
=> Add support for mbedTLS

tests/option_constants_test.py
Since curl 7.65.0, CURLOPT_SSL_ENABLE_NPN and CURLOPT_SSL_ENABLE_ALPN
are available only if libcurl is built with nghttp2 [1].
Closes: #570
[1] https://github.com/curl/curl/commit/e91e48161235272ff485ff32bd048c53af731f43#diff-72ee0eef31d053c9e6d4fb22e81d2407R2618
=> Make the test suite pass on curl without nghttp2

INSTALL.rst, doc/thread-safety.rst, setup.py, src/module.c, src/pycurl.h
This takes advantage of wolfSSL openssl compatibility layer, so all that that's needed are library detection, and inclusion of specific headers.
WolfSSL must be built with --enable-opensslextra to enable the required API, and that's being checked at build time, with a warning if disabled.
This was tested with a WRT3200ACM router (arm) running openwrt master branch, linux 4.14.105, wolfssl 3.15.7, libcurl 4.7.65.1, under a light load.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
Edit:  python versions tested: 2.7.16, 3.7.2
=> Add locking support to wolfSSL

appveyor.yml
adds the bdist_egg command to the command line for setup.py
adds twine upload to pypi for all distributions that have been made.
This requires an appveyor modification on the webgui.
=> adds the building of egg files to appveyor.

setup.py
When OpenSSL is a static library, the order of linking is important because the "ssl" library depends on the "crypto" library.
```
$ ldd /usr/lib/libssl.so
...
libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f5028b50000)
...
```
Without this change, I get the following error when importing pycurl:
```
/usr/bin/python -c "import curl"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python2.7/site-packages/curl/__init__.py", line 7, in <module>
import sys, pycurl
ImportError: /usr/lib/python2.7/site-packages/pycurl.so: undefined symbol: COMP_expand_block
```
=> Fix link order for when OpenSSL is static

.gitignore, src/pycurl.h
#599 
added #define PY_SSIZE_T_CLEAN to src/pycurl.h per Python 3.8 documentation
#################################################################
TLDR: indexes should be typed as Py_ssize_t (signed) instead of int to allow the use of full address space (64bit vs. 32bit). The conversion codes 's#' and 't#' will output Py_ssize_t if the macro PY_SSIZE_T_CLEAN is defined before Python.h is included. Use PY_SSIZE_T_CLEAN and make sure all values are correctly converted.
**Documentation**:
This warning message is new in Python 3.8 and conversion must be complete before 3.10 ...
* Changelog: https://docs.python.org/3/whatsnew/3.8.html#changes-in-the-c-api
>Use of # variants of formats in parsing or building value (e.g. PyArg_ParseTuple(), Py_BuildValue(), PyObject_CallFunction(), etc.) …
=> Fix Python 3.8 related deprecation warning 

setup.py
Will prevent users with Python 2.7 or 3.4 and older from downloading a sdist version they cannot build.
Also updated the description.
Note: supporting `python_requires` requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
=> Set python_requires='>=3.5'

setup.py
The most recent Centos versions, 7 and 8, have the same issue as
centos 6, the ssl backend is not automatically detected through
conventional ways.
So the detection of the ssl backend on Centos 6, should be used for
recent Centos versions as well.
=> Use centos6 ssl detection for other recent centos versions. Fix #619.

tests/fake-curl/libcurl/Makefile
Permit overriding `CC`, respect `*FLAGS` variables and add a `clean` target. This is needed to make it possible to build fake-curl correctly for different platforms.
=> Allow CC and CFLAGS to be overridden for  fake-curl Makefile

setup.py, src/module.c, src/pycurl.h
Support the CURLOPT_HAPROXYPROTOCOL option in pycurl.  Before this change, the option was rejected and haproxy protocol support was unusable.
=> Support the CURLOPT_HAPROXYPROTOCOL option in pycurl

src/easyopt.c
It's OK to unset `CURLOPT_PROXY` since https://github.com/curl/curl/commit/0ff89b9c3c02a911e1e5ea9a4182c373a6e0f1c7.
=> Allow unsetopt CURLOPT_PROXY

src/module.c, src/pycurl.h
Since curl 7.56, multiple SSL backends can be used in the curl library. Currently, the SSL backend check only checks the first SSL library returned by `curl_version_info` which may not necessarily be the library used by pycurl, or even be the "default" curl SSL library (in which case the check always fails).
What this pull request does, is it tries to select the SSL library that pycurl uses (via `curl_global_sslset`). This allows pycurl to still work when the SSL backend desired is present but not the default.
The return value of `curl_global_sslset` is then used to detect whether that requested library is present. If not, it will go through the list of SSL backends returned and format that into the error message. Checks are there to cover the cases where there are no backends or there …
=> Handle MultiSSL

src/module.c
Small logic error in the check - we want to error if either a valid SSL library is found at runtime or at compile time. We don't want to error when a SSL library is found in neither.
I'm very sorry for the error - I did try to cover this scenario when testing locally but must have made a mistake when doing so.
=> Fix runtime error on no-SSL builds

Makefile, tests/travis/run.sh
Both the Makefile and the Travis setup use a subshell with cd to build
fake-curl, whereas make everywhere supports -C, so make use of that
instead.
=> Use make -C for building fake-curl

src/module.c
```
src/module.c:353:25: error: lvalue required as left operand of assignment
353 |     Py_TYPE(&Curl_Type) = &PyType_Type;
|                         ^
src/module.c:354:30: error: lvalue required as left operand of assignment
354 |     Py_TYPE(&CurlMulti_Type) = &PyType_Type;
|                              ^
src/module.c:355:30: error: lvalue required as left operand of assignment
355 |     Py_TYPE(&CurlShare_Type) = &PyType_Type;
|                              ^
```
Bug: https://bugzilla.redhat.com/1890442
=> src/module.c: make the code compile against python-3.10.0a1

doc/quickstart.rst
Python 2 is end-of-life. Show only code snippets targeting Python 3.
=> docs(quickstart): only show Python 3 code

src/easy.c
Hey,
This tiny PR will fix : 
- 1 typo in `src/easy.c`
Bye! :robot:
=> docs: fix typo in src/easy.c

INSTALL.rst, README.kr.rst, README.rst, doc/index.rst, setup.py
Bintray has shut down over the weekend.
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Since a download link is not working, I've removed the links from the document.
- https://dl.bintray.com/pycurl/pycurl/ (403)
=> Remove bintray links from docs

tests/failonerror_test.py, tests/option_constants_test.py, tests/util.py
They started to return `CURLE_BAD_FUNCTION_ARGUMENT` with `curl-7.77.0`: https://github.com/curl/curl/pull/6773
=> skip tests that are incompatible with newer versions of libcurl

Makefile, README.rst, appveyor.yml, pytest.ini, requirements-dev.txt, tests/certinfo_test.py, tests/curl_object_test.py, tests/global_init_test.py, tests/header_test.py, tests/memory_mgmt_test.py, tests/multi_memory_mgmt_test.py, tests/multi_test.py, tests/option_constants_test.py, tests/procmgr.py, tests/reload_test.py, tests/resolve_test.py, tests/run.sh, tests/setopt_string_test.py, tests/setopt_test.py, tests/setopt_unicode_test.py, tests/setup_test.py, tests/share_test.py, tests/ssh_key_cb_test.py, tests/util.py
With nose being unmaintained for a long while, switch to pytest to run
the test suite.
=> Switch from nose to pytest

setup.py
Let's always prefer setuptools.setup as it generates better metadata, and fixes the following warning:
```
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
warnings.warn(msg)
```
=> Prefer setuptools.setup

src/easy.c, src/easyperform.c, src/multi.c, src/pycurl.h, tests/multi_callback_test.py
This ensures callbacks invoked by some easy-related functions have
access to the corect thread state.
Fixes callbacks invoked from:
* do_curl_perform
* do_curl_pause
* util_curl_xdecref
---
This is the fix I referred to in https://github.com/pycurl/pycurl/issues/592#issuecomment-544206524, a continuation of #594. The latter only fixed callbacks invoked by multi handles. This one fixes them when they're invoked by easy handles as well.
Practical example:
1. set socket and timer callback
2. add easy handle
3. perform a chunk of the transfer
4. pause the easy handle (do_curl_pause)
At this point callbacks will be invoked to let you know that you should stop polling for sockets associated with that easy handle. But only `easy->state` is set by `PYCURL_BEGIN_ALLOW_THREADS`, so the multi handle …
=> Fix multi callback issues: easy.pause(), easy.close(), multi.close()

src/multi.c
This is a less extreme alternative to what was proposed in issue #709.
Without callback fixes from #708 the corresponding tests produce the following warnings:
```python
multi_callback_test.py::MultiCallbackTest::test_easy_close
multi_callback_test.py:105: RuntimeWarning: multi_socket_callback failed to acquire thread
self.easy.close()
multi_callback_test.py::MultiCallbackTest::test_easy_close
multi_callback_test.py:105: RuntimeWarning: multi_timer_callback failed to acquire thread
self.easy.close()
multi_callback_test.py::MultiCallbackTest::test_easy_pause_unpause
multi_callback_test.py:85: RuntimeWarning: multi_socket_callback failed to acquire thread
self.easy.pause(pycurl.PAUSE_ALL)
```
This has already proved fruitful as I didn't realize before that `easy.close()` could also invoke …
=> Add runtime warning to multi callback GIL failure

src/multi.c, tests/multi_option_constants_test.py
Previously there was no way to unset multi options.
This patch adds `do_multi_setopt_none()`, which supports using `None` value for those libcurl options that one can set to NULL:
* CURLMOPT_SOCKETFUNCTION
* CURLMOPT_TIMERFUNCTION
* CURLMOPT_PIPELINING_SERVER_BL
* CURLMOPT_PIPELINING_SITE_BL
---
Additionally, `multi_option_constants_test.py` has also been updated:
* add missing test for setting callback options
* test setting options to `None`, with supported and unsupported options
=> Fix unsetting multi options

doc/docstrings/curl_duphandle.rst, src/easy.c, src/easyopt.c, src/module.c, src/pycurl.h, tests/app.py, tests/duphandle_test.py
@p I'm working on adding [`curl_easy_duphandle()`](https://curl.se/libcurl/c/curl_easy_duphandle.html). This is just a prototype for now. It works fine, but I stumbled upon two possible ways to go about this.
`do_curl_duphandle` must duplicate all additional values that PycURL keeps stored in a Curl object. For Python objects that's just a matter of increasing reference counts, except for attribute dictionary (easy->dict) which is copied.
The question is what to do with non-Python data: `curl_slist` and `curl_httppost`.
**Memory copies**
Right now I'm creating copies of slists (and I haven't done much yet about httppost). This requires no change to other code, but I believe it wastes memory for no reason. The user doesn't interact with these objects anyway, and they are never modified at …
=> easy.duphandle()

.github/workflows/cibuildwheel.yml
Added Linux(x86_64 and aarch64) wheel build support. 
Related to https://github.com/pycurl/pycurl/issues/738, @p Could you please review this PR?
=> Add Linux(x86_64 and aarch64) wheel build support

tests/error_test.py
I'm one of the maintainers of the curl package on Debian and I noticed a regression in pycurl's integration tests with curl 7.83.0, this is the fix:
commit message below:
tests: fix error message on error_test (for curl >= 7.83)
curl 7.83.0 removed exclamation marks from a few error messages, curl commit:
https://github.com/curl/curl/commit/6968fb9d54dc3a1aaa1b16088f038eaf5dd8b2d7
This commit adds support for the new curl release while also supporting the previous ones.
Thanks
=> tests: fix error message on error_test (for curl >= 7.83)

src/multi.c, tests/multi_test.py
Fixes an issue where (if num_results is less than the number of messages in the queue) a message can be pulled out of the queue, then the flow breaks out of the loop before the message is added to one of the returned lists.  The user therefore never sees the message.
=> Fix curl_multi_info_read flow that loses messages

.github/CONTRIBUTING.md, README.kr.rst, README.rst, doc/index.rst, setup.py
According to crt.sh, [cool.haxx.se](https://crt.sh/?q=cool.haxx.se) was retired around 2021-09-25
and [lists.haxx.se](https://crt.sh/?q=lists.haxx.se) replaced it around 2021-08-27 
This PR updates the URLs from cool.haxx.se and changes the scheme to https
=> [docs] fix mailing list address

README.rst, requirements-dev.txt, tests/app.py, tests/runwsgi.py
Bottle is not Python 3.13+ ready, see https://github.com/bottlepy/bottle/issues/1403
In Fedora, we need pycurl to be able to use fedpkg, our tool for building Fedora packages.
I plan to use this patch in Fedora temporarily until the bottle situation is resolved.
---
I do not expect this to be merged, but I opened this PR anyway, in case you or others find it useful. With this, tests pass on Python 3.13.
=> Stopgap measure for Python 3.13 testing: Minimal port of tests from bottle to flask

setup.py
To preface, in Homebrew, we are trying to build packages for macOS 15 Sequoia that use `pycurl` linked to brew `curl` and saw the wrong library (i.e. system `curl`) get picked up at runtime even though linkage is correct.
e.g. https://github.com/Homebrew/homebrew-core/actions/runs/10842043074/job/30087048897#step:4:77
```
Traceback (most recent call last):
File "/opt/homebrew/Cellar/fb-client/2.3.0_2/bin/fb", line 15, in <module>
import pycurl
ImportError: pycurl: libcurl link-time version (8.7.1) is older than compile-time version (8.10.0)
```
```
❯ otool -L /opt/homebrew/opt/fb-client/libexec/lib/python3.12/site-packages/pycurl.cpython-312-darwin.so
/opt/homebrew/opt/fb-client/libexec/lib/python3.12/site-packages/pycurl.cpython-312-darwin.so: …
```
=> Don't use `-flat_namespace` on macOS

src/easycb.c
This avoids crashing in cases where the GIL was not acquired successfully, yet we continued on like we acquired it successfully, leading to crashes.
=> Add some missing GIL checks to callback functions

.github/workflows/ci-macos.yml, pyproject.toml
Now that cibuildwheel is using shared libraries, this should be more reliable and ensure the wheel build process is tested more often.  Also, this reduces a bunch of code duplication.
=> Switch macOS CI vcpkg build to use cibuildwheel

tests/pause_test.py
It seems on this platform that SIGALRM fires after slightly less than one second, so adjust the test to ensure the wait was at least 900ms.
Fixes: #876.
=> Fix test_pause_* on OpenIndiana

.github/workflows/ci-windows.yml, .github/workflows/cibuildwheel.yml
It seems that schannel support should be enabled by default if http2 is selected, but request ssl feature anyway.
=> CI: Fix Windows vcpkg install - schannel feature removed
